In [53]:
import numpy as np

# 创建一个3x3x3的三维数组
arr = np.random.rand(5, 3)
print(arr)
print(arr.shape)

[[0.54399452 0.34034232 0.23951947]
 [0.40875993 0.30812242 0.40620704]
 [0.06127023 0.65332553 0.87454386]
 [0.54845924 0.44945782 0.83459546]
 [0.35254481 0.06456351 0.67498758]]
(5, 3)


In [55]:
data=arr[1:3,:1]
print(data)
data.shape

[[0.40875993]
 [0.06127023]]


(2, 1)